### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by meeximum** [fioritracker/installation#1]
hi,

we tried to import the SolMan transport orders, but get the following activation error?

Programm ZCL_ZFIORITRACKER_DPC=========CP, Include ZCL_ZFIORITRACKER_DPC=========CM06L: Syntaxfehler Zeile 000002
Method 'EXECUTE_ACTION' is unknown or PROTECTED orPRIVATE.

when digging into it, we see that the class CL_SADL_GW_DELEGATION_DPC has no mehtod exectue_action?

We run SolMan 7.2. Patch 9

regards
Markus

**Comment by fioritracker** [comment]
Hi,
the solution is to re-generate service. You can find instruction at:
https://help.fioritracker.org/1909SPS06/#/installation/basis-steps?id=step-2-generate-runtime-objects-for-the-zfioritracker_srv-service
